# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:18-alpine AS builder

WORKDIR /app

# Copy source files
COPY src /app/src
COPY package.json package-lock.json tsconfig.json /app/

# Install dependencies and build the project
RUN npm install && npm run build

# Production image
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package-lock.json /app/

# Install only production dependencies
RUN npm ci --omit=dev

# Default configuration (provide BITBUCKET_URL and optional BITBUCKET_TOKEN at runtime via -e)
ENV MCP_TRANSPORT=stdio
ENV PORT=3000

EXPOSE 3000

ENTRYPOINT ["node", "build/index.js"]
